# Generated by Django 3.2.4 on 2021-06-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20210606_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
