# Generated by Django 3.2.4 on 2021-06-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_delete_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
    ]
